# Use Node.js base image
FROM node:22

# Install jq
RUN apt-get update && apt-get install -y jq

# Set working directory
WORKDIR /app

# Copy source code
COPY src/ ./src/

# Copy package files
COPY package*.json ./
COPY tsconfig.json .

# Install dependencies
RUN npm install
RUN npm run build

# Expose port
EXPOSE 3000
